---
title: "Code contributions to this project from Abby Simons-Scalise"
description: |
  Using Census Data to Analyze Educational Attainment
output_dir: "_site"
site: distill::distill_website
search: TRUE
---

```{r, libraries, echo = TRUE, results = 'hide'}
#loading libraries
library(tidyverse)
library(tidycensus)
library(ggridges)
library(dplyr)
library(tigris)
options(tigris_use_cache = TRUE)
library(leaflet)
library(sf)
library(packcircles)
library(ggplot2)
library(viridis)
library(ggiraph)
library(ggbeeswarm)
library(ggiraph)
```
-------------------------------------------------
```{r, load_variables, echo = TRUE, results = 'hide'}
#installing and saving census api key 
#census_api_key("67cbcd7b6d617916475eb5bd88439380a2511582", install = TRUE)

#loading all variables (18,000+) to search and understand education variables available
all_vars_acs5 <- 
  load_variables(year = 2019, dataset = "acs5")
```
-------------------------------------------------
```{r, group_quarters3, echo = TRUE, results = 'hide'}
#defining variables related direction to adult correctional facilities
adult_prison_total = "B26106_016"
No_HS = "B26106_017"
HS_Only = "B26106_018"
Some_College = "B26106_019"
Bachelor_above = "B26106_020"
```
-------------------------------------------------
```{r, hs_only, echo = TRUE, results = 'hide'}
#calling to API to obtain only HS degrees by state & total for each state
mi_prison2 <- get_acs(
  geography = "state",
  variables = c("B26106_018"),
  geometry = TRUE,
  summary_var = "B26106_016"
) 
#mutating dataset to show percentages instead of count
mi_prison2 <- mi_prison2 %>%
  mutate(percent = 100 * (estimate / summary_est)) %>%
  select(NAME, variable, percent)
#setting up and creating interactive maps of the U.S.
df <- mi_prison2 %>%
  shift_geometry(position = "outside") %>%
  mutate(tooltip = paste(NAME, ceiling(percent), sep = ": "))

gg <- ggplot(df, aes(fill = percent)) + 
  geom_sf_interactive(aes(tooltip = tooltip, data_id = NAME), 
                      size = 0.1) + 
  scale_fill_viridis_c(option = "plasma") + 
  labs(title = "Percent of Adult Prison Population with Only High School Diploma",
       caption = "Data source: 2019 5-year ACS, US Census Bureau",
       fill = "ACS estimate") + 
  theme_void() 
  
girafe(ggobj = gg) %>%
  girafe_options(opts_hover(css = "fill:red;"), 
                 opts_zoom(max = 10))
```
-------------------------------------------------
```{r, no_hs, echo = TRUE, results = 'hide'}
#same code as above, just changing variable used
mi_prison3 <- get_acs(
  geography = "state",
  #state = "MI",
  variables = c("B26106_017"),
  geometry = TRUE,
  summary_var = "B26106_016"
) 

mi_prison3 <- mi_prison3 %>%
  mutate(percent = 100 * (estimate / summary_est)) %>%
  select(NAME, variable, percent)

df <- mi_prison3 %>%
  shift_geometry(position = "outside") %>%
  mutate(tooltip = paste(NAME, ceiling(percent), sep = ": "))

gg <- ggplot(df, aes(fill = percent)) + 
  geom_sf_interactive(aes(tooltip = tooltip, data_id = NAME), 
                      size = 0.1) + 
  scale_fill_viridis_c(option = "plasma") + 
  labs(title = "Percent of Adult Prison Population with No High School Diploma",
       caption = "Data source: 2019 5-year ACS, US Census Bureau",
       fill = "ACS estimate") + 
  theme_void() 
  
girafe(ggobj = gg) %>%
  girafe_options(opts_hover(css = "fill:red;"), 
                 opts_zoom(max = 10))
```
-------------------------------------------------
```{r, some college,echo = TRUE, results = 'hide'}
#same code as above, just changing variable used
mi_prison4 <- get_acs(
  geography = "state",
  #state = "MI",
  variables = c("B26106_019"),
  geometry = TRUE,
  summary_var = "B26106_016"
) 

mi_prison4 <- mi_prison4 %>%
  mutate(percent = 100 * (estimate / summary_est)) %>%
  select(NAME, variable, percent)

df <- mi_prison4 %>%
  shift_geometry(position = "outside") %>%
  mutate(tooltip = paste(NAME, ceiling(percent), sep = ": "))

gg <- ggplot(df, aes(fill = percent)) + 
  geom_sf_interactive(aes(tooltip = tooltip, data_id = NAME), 
                      size = 0.1) + 
  scale_fill_viridis_c(option = "plasma") + 
  labs(title = "Percent of Adult Prison Population with Some College",
       caption = "Data source: 2019 5-year ACS, US Census Bureau",
       fill = "ACS estimate") + 
  theme_void() 
  
girafe(ggobj = gg) %>%
  girafe_options(opts_hover(css = "fill:red;"), 
                 opts_zoom(max = 10))
```
-------------------------------------------------
```{r,college, echo = TRUE, results = 'hide'}
#same code as above, just changing variable used
mi_prison5 <- get_acs(
  geography = "state",
  #state = "MI",
  variables = c("B26106_020"),
  geometry = TRUE,
  summary_var = "B26106_016"
) 

mi_prison5 <- mi_prison5 %>%
  mutate(percent = 100 * (estimate / summary_est)) %>%
  select(NAME, variable, percent)


df <- mi_prison5 %>%
  shift_geometry(position = "outside") %>%
  mutate(tooltip = paste(NAME, ceiling(percent), sep = ": "))

gg <- ggplot(df, aes(fill = percent)) + 
  geom_sf_interactive(aes(tooltip = tooltip, data_id = NAME), 
                      size = 0.1) + 
  scale_fill_viridis_c(option = "plasma") + 
  labs(title = "Percent of Adult Prison Population with Bachelor's Degree or Above",
       caption = "Data source: 2019 5-year ACS, US Census Bureau",
       fill = "ACS estimate") + 
  theme_void() 
  
girafe(ggobj = gg) %>%
  girafe_options(opts_hover(css = "fill:red;"), 
                 opts_zoom(max = 10))
```
-------------------------------------------------
```{r prison_pop_MI, echo = TRUE, results = 'hide'}
#calling to API to obtain only HS degrees by state & total for each state
mi_prison <- get_acs(
  geography = "state",
  state = "MI",
  variables = c(No_HS = "B26106_017",
                HS_Only = "B26106_018",
                Some_College = "B26106_019",
                Bachelor_above = "B26106_020"),
  summary_var = "B26106_016"
) 
#mutating for percentages
mi_prison <- mi_prison %>%
  mutate(percent = 100 * (estimate / summary_est)) %>%
  select(NAME, variable, percent)
#bar chart to show educational levels by percent for MI
mi_prison %>%
  ggplot( aes(x=variable, y=ceiling(percent))) +
  geom_bar(stat="identity", fill="#f68060", alpha=.6, width=.4) +
  coord_flip() +
  xlab("") +
  theme_bw()+
  geom_label(aes(label = ceiling(percent)))+
  labs(title = "Percent of MI Prison Population by Educational Attainment", 
     subtitle = "2019 5-year ACS estimates", 
     y = "Percent", 
     x = "Education Level", 
     caption = "Source: ACS Data Table B26106 via the tidycensus R package") 


```
-------------------------------------------------
```{r prison_pie_MI, echo = TRUE, results = 'hide'}
#pie chart of same table from bar chart
mi_prison %>%
  ggplot(
  aes(x= "", y = percent, fill=variable)) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) +
  theme_void()+
  scale_fill_brewer()+
  geom_label(aes(label = ceiling(percent)),
            position = position_stack(vjust = 0.5),
            show.legend = FALSE) +
  labs(title = "Percent of MI Adult Prison Population by Educational Attainment", 
     subtitle = "2019 5-year ACS estimates")
```
-------------------------------------------------
```{r, define_variables_jobs,echo = TRUE, results = 'hide'}

#enrolled in school, defining variables
FnoHS_employed <- ("B14005_027")
FnoHS_unemployed <- ("B14005_028")
FnoHS_notinlaborforce <- ("B14005_029")
FHS_employed <- ("B14005_023")
FHS_unemployed <- ("B14005_024")
FHS_notinlaborforce <-("B14005_025")
MnoHS_employed <- ("B14005_013")
MnoHS_unemployed <- ("B14005_014")
MnoHS_notinlaborforce <-("B14005_015")
MHS_employed <- ("B14005_009")
MHS_unemployed <- ("B14005_010")
MHS_notinlaborforce <- ("B14005_011")

employed <- c(Male_No_HS = "B14005_013", 
              Male_HS = "B14005_009", 
              Female_No_HS = "B14005_027", 
              Female_HS = "B14005_023")
unemployed <- c(Male_No_HS = "B14005_014", 
              Male_HS = "B14005_010", 
              Female_No_HS = "B14005_028", 
              Female_HS = "B14005_024")
nilf <- c(Male_No_HS = "B14005_015", 
              Male_HS = "B14005_011", 
              Female_No_HS = "B14005_029", 
              Female_HS = "B14005_025")

```
-------------------------------------------------
```{r, labor_force_plots_males,echo = TRUE, results = 'hide'}

#males in michigan, heat maps
MI_male <- get_acs(geography = "county", 
                      variables = c(Employed_NoHS ="B14005_013",
                                    Employed_HS = "B14005_009",
                                    Unemployed_NoHS = "B14005_014",
                                    Unemployed_HS ="B14005_010",
                                    Notinlaborforce_NoHS = "B14005_015",
                                    Notinlaborforce_HS ="B14005_011"),
                      state = "MI", geometry = TRUE,
                      summary_var = "B14005_003") 

MI_male2 <- MI_male %>% 
  mutate(Percent = 100 * estimate / summary_est)

MI_male2 %>% 
  ggplot(aes(fill = Percent)) +
    geom_sf(color = NA) +
    facet_wrap(~variable, nrow = 2, ncol =3) +
    scale_fill_viridis_c(option = "plasma")+
    labs(title = "Percent of Males in Michigan",
         subtitle = "By High School Graduation and Employment Status")

```
-------------------------------------------------
```{r, labor_force_plots_females,echo = TRUE, results = 'hide'}

#females in michigan, heat maps
MI_female <- get_acs(geography = "county", 
                      variables = c(Employed_NoHS ="B14005_027",
                                    Employed_HS = "B14005_023",
                                    Unemployed_NoHS = "B14005_028",
                                    Unemployed_HS ="B14005_024",
                                    Notinlaborforce_NoHS = "B14005_029",
                                    Notinlaborforce_HS ="B14005_025"),
                      state = "MI", geometry = TRUE,
                      summary_var = "B14005_003") 

MI_female2 <- MI_female %>% 
  mutate(Percent = 100 * estimate / summary_est)

MI_female2 %>% 
  ggplot(aes(fill = Percent)) +
    geom_sf(color = NA) +
    facet_wrap(~variable, ncol = 3) +
    scale_fill_viridis_c(option = "plasma")+
    labs(title = "Percent of Females in Michigan",
         subtitle = "By High School Graduation and Employment Status")

```
-------------------------------------------------
```{r, leaflet_MI,echo = TRUE, results = 'hide'}
#interactive leaflet map
mi1 <- get_acs(geography = "county", 
               variables = c(Notinlaborforce_HS ="B14005_025"), 
               state = "MI", 
               geometry = TRUE) %>%
  st_transform(4326)

mi2 <- get_acs(geography = "tract", 
               variables = c(Notinlaborforce_HS ="B14005_025"), 
               state = "MI", 
               geometry = TRUE) %>%
  st_transform(4326)

bins <- c(0,20,40,60,80,100,120,140,160,180,200,300,400,500,600,700,800)

pala <- colorBin("viridis", mi1$estimate, bins = bins)

leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(data = mi1, stroke = FALSE, smoothFactor = 0.2, 
              color = ~pala(estimate), 
              label = ~as.character(estimate), 
              fillOpacity = 0.8, 
              group = "Counties") %>%
  addPolygons(data = mi2, stroke = FALSE, smoothFactor = 0.2, 
              color = ~pala(estimate), 
              label = ~as.character(estimate), 
              fillOpacity = 0.8, 
              group = "Tracts") %>%
  addLegend("bottomright", pal = pala, values = mi1$estimate, 
            title = "Females in MI: Without HS Diploma") %>%
  addLayersControl(overlayGroups = c("Tracts", "Counties")) %>% 
  hideGroup("Tracts")
```  
-------------------------------------------------
```{r variables,echo = TRUE, results = 'hide'}
#shiny app with dropdown to select different variables
#displays heatmap

library(tidycensus)
library(shiny)
library(leaflet)
library(tidyverse)

twin_cities_race <- get_acs(
    geography = "tract",
    variables = c(Female_Employed_NoHS ="B14005_027",
                  Female_Employed_HS = "B14005_023",
                  Female_Unemployed_NoHS = "B14005_028",
                  Female_Unemployed_HS ="B14005_024",
                  Female_Notinlaborforce_NoHS = "B14005_029",
                  Female_Notinlaborforce_HS ="B14005_025",
                  Male_Employed_NoHS ="B14005_013",
                  Male_Employed_HS = "B14005_009",
                  Male_Unemployed_NoHS = "B14005_014",
                  Male_Unemployed_HS ="B14005_010",
                  Male_Notinlaborforce_NoHS = "B14005_015",
                  Male_Notinlaborforce_HS ="B14005_011"
    ),
    state = "MI",
    county = c("Kent", "Ionia", "Ottawa","Muskegon","Montcalm","Newaygo","Allegan","Barry", "Kalamazoo", "Van Buren", "Oceana", "Lake", "Mason", "Berrien","Cass"),
    geometry = TRUE
) 

groups <- c("Male_Employed_HS" = "Male_Employed_HS",
            "Female_Employed_NoHS" = "Female_Employed_NoHS",
            "Female_Employed_HS" = "Female_Employed_HS",
            "Female_Unemployed_NoHS" = "Female_Unemployed_NoHS",
            "Female_Unemployed_HS" = "Female_Unemployed_HS",
            "Female_Notinlaborforce_NoHS" = "Female_Notinlaborforce_NoHS",
            "Male_Employed_NoHS" = "Male_Employed_NoHS",
            "Male_Notinlaborforce_NoHS" = "Male_Notinlaborforce_NoHS",
            "Male_Notinlaborforce_HS" = "Male_Notinlaborforce_HS",
            "Male_Unemployed_HS" = "Male_Unemployed_HS",
            "Male_Unemployed_NoHS" = "Male_Unemployed_NoHS"
            )

ui <- fluidPage(
    sidebarLayout(
        sidebarPanel(
            selectInput(
                inputId = "group",
                label = "Select variable",
                choices = groups
            )
        ),
        mainPanel(
            leafletOutput("map", height = "600")
        )
    )
)

server <- function(input, output) {

    group_to_map <- reactive({
        filter(twin_cities_race, variable == input$group)
    })
    

    output$map <- renderLeaflet({
        
        leaflet(options = leafletOptions(zoomControl = FALSE)) %>%
            addProviderTiles(providers$Stamen.TonerLite) %>%
            setView(lng = -85.5,
                    lat = 43,
                    zoom = 8.5)
        
    })
    
    observeEvent(input$group, {
        
        pal <- colorNumeric("viridis", group_to_map()$estimate)
        
        leafletProxy("map") %>%
            clearShapes() %>%
            clearControls() %>%
            addPolygons(data = group_to_map(),
                        color = ~pal(estimate),
                        weight = 0.5,
                        fillOpacity = 0.5,
                        smoothFactor = 0.2,
                        label = ~estimate) %>%
            addLegend(
                position = "bottomright",
                pal = pal,
                values = group_to_map()$estimate,
                title = "Population in West Michigan"
            )
    })
    
}

shinyApp(ui = ui, server = server)
```
----------------------------------------
```{r, pov1, echo = TRUE, results = 'hide'}
below_poverty <- get_acs(
  geography = "county",
  state = "MI",
  variables = c(Married_noHS = "B17018_004",
                Single_Male_noHS = "B17018_010",
                Single_Female_noHS = "B17018_015",
                Married_HS = "B17018_005",
                Single_Male_HS = "B17018_011",
                Single_Female_HS = "B17018_016",
                Married_Some_College = "B17018_006",
                Single_MSome_College = "B17018_012",
                Single_FSome_College = "B17018_017",
                Married_College = "B17018_007",
                Single_Male_College = "B17018_013",
                Single_Female_College = "B17018_018"),
  summary_var = "B17018_002"
) 

below_pov_percents <- below_poverty %>%
  mutate(percent = 100 * (estimate / summary_est)) %>%
  select(NAME, variable, percent)

no_HS <- get_acs(
  geography = "county",
  state = "MI",
  variables = c(Below_Married_noHS = "B17018_004",
                Below_Single_Male_noHS = "B17018_010",
                Below_Single_Female_noHS = "B17018_015",
                Above_Married_noHS = "B17018_021",
                Above_Single_Male_noHS = "B17018_027",
                Above_Single_Female_noHS = "B17018_032"),
  summary_var = "B17018_001"
) 
noHS_percents <- no_HS %>%
  mutate(percent = 100 * (estimate / summary_est)) %>%
  select(NAME, variable, percent)

HS <- get_acs(
  geography = "county",
  state = "MI",
  variables = c(Below_Married_HS = "B17018_005",
                Below_Single_Male_HS = "B17018_011",
                Below_Single_Female_HS = "B17018_016",
                Above_Married_HS = "B17018_022",
                Above_Single_Male_HS = "B17018_028",
                Above_Single_Female_HS = "B17018_033"),
  summary_var = "B17018_001"
)

HS_percents <- HS %>%
  mutate(percent = 100 * (estimate / summary_est)) %>%
  select(NAME, variable, percent)


somecol <- get_acs(
  geography = "county",
  state = "MI",
  variables = c(Below_Married_somecol = "B17018_006",
                Below_Single_Male_somecol = "B17018_012",
                Below_Single_Female_somecol = "B17018_017",
                Above_Married_somecol = "B17018_023",
                Above_Single_Male_somecol = "B17018_029",
                Above_Single_Female_somecol = "B17018_034"),
  summary_var = "B17018_001"
)

somecol_percents <- somecol %>%
  mutate(percent = 100 * (estimate / summary_est)) %>%
  select(NAME, variable, percent)

college <- get_acs(
  geography = "county",
  state = "MI",
  variables = c(Below_Married_college = "B17018_007",
                Below_Single_Male_college = "B17018_013",
                Below_Single_Female_college = "B17018_018",
                Below_Married_noHS = "B17018_004",
                Above_Married_college = "B17018_024",
                Above_Single_Male_college = "B17018_023",
                Above_Single_Female_college = "B17018_035"),
  summary_var = "B17018_001"
)

college_percents <- college %>%
  mutate(percent = 100 * (estimate / summary_est)) %>%
  select(NAME, variable, percent)

```
-------------------------------------
```{r pov2, echo = TRUE, results = 'hide'}
#plot no hs
ggplot(noHS_percents, aes(x = `percent`, y = `variable` , fill = ..x..)) +
  geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01) +
  scale_fill_viridis(name = "Inferno", option = "B") +
  labs(title = 'Percent of Population Below High School') +
  theme_ipsum() +
    theme(
      legend.position="none",
      panel.spacing = unit(0.1, "lines"),
      strip.text.x = element_text(size = 8)
    )

# Plot high school
ggplot(HS_percents, aes(x = `percent`, y = `variable` , fill = ..x..)) +
  geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01) +
  scale_fill_viridis(name = "Temp. [F]", option = "C") +
  labs(title = 'Percent of Population with High School Diploma') +
  theme_ipsum() +
    theme(
      legend.position="none",
      panel.spacing = unit(0.1, "lines"),
      strip.text.x = element_text(size = 8)
    )

# Plot some college
ggplot(somecol_percents, aes(x = `percent`, y = `variable` , fill = ..x..)) +
  geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01) +
  scale_fill_viridis(name = "Inferno", option = "A") +
  labs(title = 'Percent of Population with Some College') +
  theme_ipsum() +
    theme(
      legend.position="none",
      panel.spacing = unit(0.1, "lines"),
      strip.text.x = element_text(size = 8)
    )

# Plot college
ggplot(college_percents, aes(x = `percent`, y = `variable` , fill = ..x..)) +
  geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01) +
  scale_fill_viridis(name = "Inferno", option = "D") +
  labs(title = 'Percent of Population with Bachelor or Higher') +
  theme_ipsum() +
    theme(
      legend.position="none",
      panel.spacing = unit(0.1, "lines"),
      strip.text.x = element_text(size = 8)
    )
```
----------------------------------

```{r, pov3, echo = TRUE, results = 'hide'}
library(ggbeeswarm)

married <- get_acs(
  geography = "tract",
  state = "MI",
  variables = c(Below_Married_college = "B17018_007",
                Below_Married_somecol = "B17018_006",
                Below_Married_HS = "B17018_005",
                Above_Married_college = "B17018_024",
                Above_Married_somecol = "B17018_023",
                Above_Married_HS = "B17018_022",
                Above_Married_noHS = "B17018_021"),
  summary_var = "B17018_001"
) %>%
  #group_by(GEOID) %>%
  #filter(estimate == max(estimate, na.rm = TRUE)) %>%
  #ungroup() %>%
  filter(estimate != 0)

ggplot(married, aes(x = variable, y = estimate, color = estimate)) +
  geom_quasirandom(alpha = 0.5) + 
  coord_flip() + 
  theme_minimal(base_size = 13) + 
  scale_color_viridis_c(guide = "none")  + 
  labs(x = "Variable", 
       y = "Population Estimate", 
       title = "Estimates on Population that are Married", 
       subtitle = "Census tracts, Michigan", 
       caption = "Data source: 2015-2019 ACS")

```
-------------------------------------
```{r, pov5, echo = TRUE, results = 'hide'}
married2 <- get_acs(
  geography = "tract",
  variables = c(
                Above_Married_college = "B17018_024",
                Above_Married_somecol = "B17018_023",
                Above_Married_HS = "B17018_022",
                Above_Married_noHS = "B17018_021"),
  state = "MI", geometry = TRUE,
  summary_var = "B17018_001"
)
marriedpercent <- married2 %>% 
  mutate(percent = 100 * estimate / summary_est)%>%
  select(NAME, variable, percent)


marriedpercent %>% 
  ggplot(aes(fill = `percent`)) +
    geom_sf(color = NA) +
    facet_wrap(~variable, ncol = 2) +
    scale_fill_viridis(name = "Inferno", option = "D")+
    labs(title = "Percent Population Married in MI",
         subtitle = "By household type (Above Poverty Level)")
```